// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function GetAPIKey():Promise<string>;

export function GetHistory():Promise<Array<main.EmailHistory>>;

export function SaveAPIKey(arg1:string):Promise<void>;

export function SendEmail(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string):Promise<string>;
