// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function SendEmail(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3, arg4, arg5);
}
